version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data

  # ①追記 - nginx
  web:
    image: nginx:1.20-alpine  # コンテナを起動させるイメージを指定, nginx | Docker Hubを指定
    ports: # nginxへ外(ホスト側)からコンテナ内へアクセスさせるため公開用のポートを設定する
      - 8080:80 # ホスト側：コンテナ側
    volumes: # ホスト側にあるディレクトリ、ファイルをコンテナ内へマウントさせている
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data 
  # ②追記 - MySQL
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33060:3306

volumes:
  db-store: